import sqlite3

connection = sqlite3.connect('..\\p2i.db')
cursor = connection.cursor()

cursor.execute("DROP TABLE IF EXISTS Candidat;")
cursor.execute("DROP TABLE IF EXISTS ville;")
cursor.execute("DROP TABLE IF EXISTS admissions;")
cursor.execute("DROP TABLE IF EXISTS CMT_Oraux;")
cursor.execute("DROP TABLE IF EXISTS CMT_Oraux_Spe;")
cursor.execute("DROP TABLE IF EXISTS Oraux_CCS;")
cursor.execute("DROP TABLE IF EXISTS Oraux_CCMP;")
cursor.execute("DROP TABLE IF EXISTS Classes_CMT_spe_XXX;")
cursor.execute("DROP TABLE IF EXISTS inscription;")
cursor.execute("DROP TABLE IF EXISTS pays;")
cursor.execute("DROP TABLE IF EXISTS nation;")
cursor.execute("DROP TABLE IF EXISTS concours;")
cursor.execute("DROP TABLE IF EXISTS bac;")
cursor.execute("DROP TABLE IF EXISTS serie_bac;")
cursor.execute("DROP TABLE IF EXISTS csp;")
cursor.execute("DROP TABLE IF EXISTS Oral_autres;")
cursor.execute("DROP TABLE IF EXISTS Resultat_ecrit;")
cursor.execute("DROP TABLE IF EXISTS bonification;")
cursor.execute("DROP TABLE IF EXISTS ListeEcoles;")
cursor.execute("DROP TABLE IF EXISTS ListeEtablissements;")
cursor.execute("DROP TABLE IF EXISTS listeVoeux;")
cursor.execute("DROP TABLE IF EXISTS voie_classe;")
cursor.execute("DROP TABLE IF EXISTS listeEtasRe;")

connection.commit()
connection.close()
